# Generated by Django 4.2.8 on 2024-02-16 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_category_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ccheckout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre del tipo de entrega')),
                ('description', models.CharField(max_length=250, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='precio')),
                ('Horario', models.CharField(max_length=50, verbose_name='Horario de entrega')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_address_1',
            field=models.CharField(max_length=50, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_address_2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Dirección alterntiva'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_city',
            field=models.CharField(max_length=50, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_country',
            field=models.CharField(max_length=50, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_name',
            field=models.CharField(max_length=50, verbose_name='Nombre para facturación'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_state',
            field=models.CharField(max_length=2, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_zip',
            field=models.CharField(max_length=10, verbose_name='Código postal'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='dirección ip'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='última actualización'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address_1',
            field=models.CharField(max_length=50, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address_2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Dirección alternativa'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(max_length=50, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_country',
            field=models.CharField(max_length=50, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_name',
            field=models.CharField(max_length=50, verbose_name='Nombre para la entrega'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_state',
            field=models.CharField(max_length=2, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_zip',
            field=models.CharField(max_length=10, verbose_name='Código postal'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Solicitada'), (2, 'Procesando'), (3, 'Transportando'), (4, 'Cancelada')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(max_length=20, verbose_name='Id de la transacción'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccheckout.order', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Cantidad'),
        ),
    ]
