# Generated by Django 4.2.8 on 2024-02-16 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccheckout', '0002_shippingtype_alter_order_billing_address_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_id', models.CharField(max_length=50, verbose_name='Nombre del tipo de entrega')),
                ('description', models.CharField(max_length=250, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Costo')),
                ('services_hours', models.CharField(max_length=50, verbose_name='Horario de entrega')),
            ],
            options={
                'verbose_name': 'Tipo de entrega',
            },
        ),
        migrations.DeleteModel(
            name='ShippingType',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address_1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address_2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_zip',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address_1',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address_2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Dirección alternativa'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_state',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ccheckout.deliverytype', verbose_name='Tipo de entrega'),
        ),
    ]
