# Generated by Django 4.2.8 on 2024-03-05 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccheckout', '0004_remove_order_delivery_type_order_delivery_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Orden de compra'},
        ),
    ]
