# Generated by Django 3.2 on 2024-04-02 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccheckout', '0005_alter_order_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_address_1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_address_2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_zip',
        ),
    ]
