# Generated by Django 3.2 on 2024-04-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccheckout', '0006_auto_20240402_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_price',
            field=models.IntegerField(default=0, verbose_name='Precio de envío]'),
        ),
    ]
