# Generated by Django 3.2 on 2024-04-23 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccheckout', '0007_order_delivery_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryType',
        ),
    ]
