# Generated by Django 3.2 on 2024-05-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccheckout', '0008_delete_deliverytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_price',
            field=models.IntegerField(default=0, verbose_name='Precio de envío'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='Dirección ip'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Solicitada'), (2, 'Procesando'), (3, 'Transportando'), (4, 'Cancelada'), (5, 'Cancelada')], default=1, verbose_name='Estado'),
        ),
    ]
