# Generated by Django 3.2 on 2024-05-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccheckout', '0010_order_delivery_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='store_name',
            field=models.CharField(default='Envío Habana', max_length=250, verbose_name='Forma de entrega'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Solicitada'), (1, 'Procesando'), (2, 'Transportando'), (3, 'Cancelada'), (4, 'Entregada'), (5, 'Devuelta')], default=0, verbose_name='Estado'),
        ),
    ]
