# Generated by Django 3.2 on 2024-05-08 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_store_price'),
        ('ccheckout', '0010_order_delivery_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.store', verbose_name='Tipo de entrega'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Solicitada'), (1, 'Procesando'), (2, 'Transportando'), (3, 'Cancelada'), (4, 'Entregada'), (5, 'Devuelta')], default=0, verbose_name='Estado'),
        ),
    ]
