# Generated by Django 3.2 on 2024-05-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccheckout', '0011_auto_20240508_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='store',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='store_name',
            field=models.CharField(default='Envío Habana', max_length=250, verbose_name='Forma de entrega'),
        ),
    ]
