# Generated by Django 3.2 on 2024-05-09 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccheckout', '0011_auto_20240509_0355'),
        ('ccheckout', '0012_auto_20240508_1232'),
    ]

    operations = [
    ]
