# Generated by Django 3.2 on 2024-06-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccheckout', '0013_merge_0011_auto_20240509_0355_0012_auto_20240508_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_url',
            field=models.URLField(default='', verbose_name='URL de pago'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Solicitada'), (1, 'Procesado'), (2, 'Pagado'), (3, 'Transportando'), (4, 'Cancelada'), (5, 'Entregada'), (6, 'Devuelta')], default=0, verbose_name='Estado'),
        ),
    ]
