# Generated by Django 3.2 on 2024-07-30 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_auto_20240715_1855'),
        ('ccheckout', '0014_auto_20240628_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.store', verbose_name='Tipo de entrega'),
        ),
    ]
