# Generated by Django 3.2 on 2024-08-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccheckout', '0015_order_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='store_name',
            field=models.CharField(default='Envío Habana', max_length=20, verbose_name='Nombre del tipo de entrega'),
        ),
    ]
