# Generated by Django 3.2 on 2024-08-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccheckout', '0016_order_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Solicitada'), (1, 'Procesada'), (2, 'Pagada'), (3, 'Transportanda'), (4, 'Cancelada'), (5, 'Entregada'), (6, 'Devuelta')], default=0, verbose_name='Estado'),
        ),
    ]
