# Generated by Django 3.2 on 2024-09-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccheckout', '0017_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='store_name',
            field=models.CharField(default='Envío Habana', max_length=200, verbose_name='Nombre del tipo de entrega'),
        ),
    ]
