# Generated by Django 3.2 on 2024-09-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccheckout', '0019_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_phone',
            field=models.CharField(default=5355555555, max_length=20, verbose_name='Teléfono de contacto para la entrega'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_ws',
            field=models.CharField(default=5355555555, max_length=20, verbose_name='Teléfono de WhatsApp para la entrega'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_city',
            field=models.CharField(default=0, max_length=20, verbose_name='Ciudad del banco de la tarjeta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_email',
            field=models.EmailField(default=0, max_length=50, verbose_name='Correo electrónico de contacto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del beneficiario de la tarjeta'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_phone',
            field=models.CharField(default=5355555555, max_length=20, verbose_name='Teléfono de contacto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_postCode',
            field=models.CharField(default=78622, max_length=20, verbose_name='Código Postal'),
            preserve_default=False,
        ),
    ]
