# Generated by Django 3.2 on 2024-09-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccheckout', '0020_auto_20240913_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_phone',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_ws',
            field=models.CharField(max_length=20, verbose_name='Teléfono WhatsApp'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_city',
            field=models.CharField(help_text='Ciudad del banco de la tarjeta', max_length=20, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_email',
            field=models.EmailField(max_length=50, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del beneficiario'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_phone',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
    ]
