# Generated by Django 3.2 on 2024-09-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccheckout', '0021_auto_20240914_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='USD', max_length=3, verbose_name='Tipo de moneda'),
        ),
    ]
