# Generated by Django 3.2 on 2024-10-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccheckout', '0024_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(help_text='Ciudad del banco de la tarjeta', max_length=20, verbose_name='Nro. Transacción'),
        ),
    ]
