# Generated by Django 3.2 on 2024-09-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Banner')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='Banners', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banners',
                'ordering': ['-title'],
            },
        ),
    ]
