# Generated by Django 3.2 on 2024-09-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0002_banner_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='main',
            field=models.BooleanField(default=False, help_text='Puede estar marcado un solo banner como principal', verbose_name='Principal'),
        ),
    ]
