# Generated by Django 3.2 on 2024-03-27 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_auto_20240324_1656'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='delivery',
            field=models.ForeignKey(default='Enviar', null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
    ]
