# Generated by Django 3.2 on 2024-03-27 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitem_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='delivery',
        ),
    ]
