# Generated by Django 4.2.8 on 2024-03-06 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_profile_avatar_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='client_type',
            field=models.IntegerField(choices=[(1, 'Comprador ocasional'), (2, 'Comprador de materias primas'), (3, 'Comprador al mayor')], default=1, verbose_name='Tipo de cliente'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biografía'),
        ),
    ]
