# Generated by Django 3.2 on 2024-09-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20240329_2334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user'], 'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AddField(
            model_name='profile',
            name='cid',
            field=models.CharField(blank=True, help_text='Número de identificación', max_length=20, null=True, verbose_name='Número de identidad'),
        ),
        migrations.AddField(
            model_name='profile',
            name='money_type',
            field=models.IntegerField(choices=[(1, 'USD'), (2, 'CUP'), (3, 'MLC')], default=1, help_text='En cualquier momento puede cambiarla', verbose_name='Tipo de moneda'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Número de móvil'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ws',
            field=models.CharField(blank=True, help_text='Número de teléfono para WhatsApp', max_length=15, null=True, verbose_name='Número para WhatsApp'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='client_type',
            field=models.IntegerField(choices=[(1, 'Comprador'), (2, 'Productor'), (3, 'Distribuidor')], default=1, help_text='Puede cambiarlo cuando desee en su perfil', verbose_name='Tipo de cliente'),
        ),
    ]
