# Generated by Django 3.2 on 2024-09-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20240909_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cid',
            field=models.CharField(default=11111111111, help_text='Número de identificación', max_length=20, unique='True', verbose_name='Número de identidad'),
            preserve_default=False,
        ),
    ]
