# Generated by Django 3.2 on 2024-09-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20240910_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cid',
            field=models.CharField(help_text='Número de identificación', max_length=20, verbose_name='Número de identidad'),
        ),
    ]
