# Generated by Django 3.2 on 2024-09-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_alter_profile_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cid',
            field=models.CharField(help_text='Número de identificación', max_length=20, unique='True', verbose_name='Número de identidad'),
        ),
    ]
