# Generated by Django 3.2 on 2024-10-10 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0017_auto_20240910_1658'),
        ('registration', '0010_alter_profile_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='prefered_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.store', verbose_name='Forma de entrega preferida'),
        ),
    ]
