# Generated by Django 3.2 on 2024-11-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_profile_prefered_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='client_type',
            field=models.IntegerField(choices=[(0, 'Comprador'), (1, 'Productor'), (2, 'Distribuidor'), (3, 'Vendedor')], default=0, help_text='Puede cambiarlo cuando desee en su perfil', verbose_name='Tipo de cliente'),
        ),
    ]
