# Generated by Django 4.2.8 on 2024-01-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.CharField(help_text='Contenido de la descripción de las palabras clave', max_length=255, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_keywords',
            field=models.CharField(help_text='Conjunto de palabras clave separadas por coma', max_length=255, verbose_name='Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Valor único de cada producto creado a partir del nombre.', unique=True),
        ),
    ]
