# Generated by Django 4.2.8 on 2024-03-05 15:20

import catalog.models
import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.AddField(
            model_name='product',
            name='gname',
            field=models.CharField(default='', help_text='Nombre genérico del producto.', max_length=255, verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_datasheet',
            field=models.FileField(blank=True, null=True, upload_to=catalog.models.generate_path, validators=[catalog.validators.valid_extension], verbose_name='Ficha técnica del producto'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog', verbose_name='Imagen de la categoría]'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog', verbose_name='Imagen del producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Nombre único para cada tipo de producto, incluye presentación (500ml, 1l, Tonelada).', max_length=255, unique=True, verbose_name='Nombre único'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(help_text='código específico del producto.', max_length=50, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='Valor único para la página de los productos, creada a partir del nombre único.', max_length=255, unique=True, verbose_name='Nombre para URL'),
        ),
    ]
