# Generated by Django 4.2.8 on 2024-03-11 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_category_image_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Categorías', verbose_name='Imagen de la categoría'),
        ),
    ]
