# Generated by Django 3.2 on 2024-03-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_category_options_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Categorías', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Valor único de cada producto creado a partir del nombre', unique=True, verbose_name='codigo'),
        ),
    ]
