# Generated by Django 3.2 on 2024-05-09 03:55

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20240506_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Descripción'),
        ),
    ]
