# Generated by Django 3.2 on 2024-05-08 18:31

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_product_presentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='product',
            name='presentation',
            field=models.CharField(default='', help_text='Presentación (con unidad de medida).', max_length=50, verbose_name='Presentación'),
        ),
    ]
