# Generated by Django 3.2 on 2024-05-09 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_product_description'),
        ('catalog', '0015_auto_20240508_1831'),
    ]

    operations = [
    ]
