# Generated by Django 3.2 on 2024-05-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_merge_20240509_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_feedstock',
            field=models.BooleanField(default=False, verbose_name='Materia prima'),
        ),
    ]
