# Generated by Django 3.2 on 2024-08-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_category_is_feedstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Cantidad del producto en inventarios'),
        ),
        migrations.AddField(
            model_name='product',
            name='reserved',
            field=models.IntegerField(default=0, verbose_name='Cantidad reservados para comprar'),
        ),
    ]
