# Generated by Django 3.2 on 2024-09-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_product_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price_cup',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio CUP'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_mlc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio MLC'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio USD'),
        ),
    ]
