# Generated by Django 3.2 on 2024-09-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20240909_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_whole',
            field=models.IntegerField(default=100, help_text='Cantidad mínima del producto para venta mayorista', verbose_name='Mínimo mayorista'),
        ),
        migrations.AddField(
            model_name='product',
            name='priceW_cup',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio mayorista CUP'),
        ),
        migrations.AddField(
            model_name='product',
            name='priceW_mlc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio mayorista MLC'),
        ),
        migrations.AddField(
            model_name='product',
            name='priceW_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio mayorista USD'),
        ),
    ]
