# Generated by Django 3.2 on 2024-10-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20240918_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_feedstock',
            field=models.BooleanField(default=False, verbose_name='Materia prima'),
        ),
    ]
