# Generated by Django 3.2 on 2024-10-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_product_is_feedstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_CUP',
            field=models.BooleanField(default=True, verbose_name='Disponible en CUP'),
        ),
        migrations.AddField(
            model_name='product',
            name='available_MLC',
            field=models.BooleanField(default=True, verbose_name='Disponible en MLC'),
        ),
    ]
