# Generated by Django 3.2 on 2024-09-23 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_alter_price_is_active'),
        ('cart', '0003_remove_cartitem_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.price', verbose_name='Cálculo de precio'),
        ),
    ]
