# Generated by Django 3.2 on 2024-09-23 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
    ]
