# Generated by Django 3.2 on 2024-09-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio base USD')),
                ('change_usd_cup', models.IntegerField(default=120, verbose_name='Cambio USD a CUP')),
                ('change_usd_mlc', models.DecimalField(decimal_places=2, default=1.0, max_digits=9, verbose_name='Cambio USD a MLC')),
                ('whole_discount', models.IntegerField(default=30, verbose_name='Porciento de descuento para ventas mayoristas (cantidad de productos)')),
                ('min_quantity_whole', models.IntegerField(default=20, verbose_name='Cantidad mínima para ventas mayoristas.(Unidades de un mismo producto)')),
                ('amunt_discount', models.IntegerField(default=10, verbose_name='Porciento de descuento para ventas mayoristas. (Monto de la compra)')),
                ('min_quantity_amount', models.IntegerField(default=4200, verbose_name='Monto mínimo para descuento mayorista (En USD)')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activo')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
