# Generated by Django 3.2 on 2024-09-18 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='usd',
        ),
    ]
