# Generated by Django 3.2 on 2024-09-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_remove_price_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Actual'),
        ),
    ]
