# Generated by Django 3.2 on 2024-10-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_alter_price_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='min_delivery_free',
            field=models.IntegerField(default=250, verbose_name='Monto mínimo para envío gratis.'),
        ),
    ]
