# Generated by Django 4.2.8 on 2024-03-05 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0007_remove_product_quantity_remove_product_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de almacen')),
                ('hours', models.CharField(max_length=255, verbose_name='Horario de entrega')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección de entrega')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.IntegerField(default=0, verbose_name='Cantidad a la venta')),
                ('reserved', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad de vendidos sin entregar')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Producto a vender')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Almacén de ventas')),
            ],
        ),
    ]
