# Generated by Django 4.2.8 on 2024-03-05 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_sales',
            options={'ordering': ['product'], 'verbose_name': 'producto en venta', 'verbose_name_plural': 'productos en venta'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'almacén', 'verbose_name_plural': 'almacenes'},
        ),
    ]
