# Generated by Django 4.2.8 on 2024-03-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Tiendas', verbose_name='Imagen del punto de venta'),
        ),
    ]
