# Generated by Django 4.2.8 on 2024-03-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_store_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='slug',
            field=models.SlugField(help_text='Valor único de cada tipo de entrega, creado a partir del nombre.', unique=True, verbose_name='código para URL'),
        ),
    ]
