# Generated by Django 4.2.8 on 2024-03-06 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_alter_store_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='slug',
        ),
    ]
