# Generated by Django 4.2.8 on 2024-03-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_remove_store_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='slug',
            field=models.SlugField(blank=True, default=models.CharField(max_length=255, unique=True, verbose_name='Nombre de almacen'), help_text='Valor único de cada tipo de entrega, creado a partir del nombre.', null=True, unique=True, verbose_name='código para URL'),
        ),
    ]
