# Generated by Django 3.2 on 2024-03-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_auto_20240324_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='price',
            field=models.FloatField(default=0, verbose_name='Precio de entrega'),
        ),
    ]
