# Generated by Django 3.2 on 2024-07-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_store_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_sales',
            name='product_store',
            field=models.CharField(default='', help_text='Nombre único para cada tipo de producto en cada almacén.', max_length=255, verbose_name='Nombre único'),
        ),
    ]
