# Generated by Django 3.2 on 2024-08-22 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_auto_20240715_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_sales',
            old_name='reserved',
            new_name='sold',
        ),
    ]
