# Generated by Django 3.2 on 2024-08-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0013_rename_reserved_product_sales_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_sales',
            name='reserved',
            field=models.IntegerField(default=0, verbose_name='Cantidad de reservados, sin pagar'),
        ),
        migrations.AlterField(
            model_name='product_sales',
            name='sold',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad de vendidos por entregar'),
        ),
    ]
