# Generated by Django 3.2 on 2024-09-04 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0014_auto_20240826_1252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_sales',
            options={'ordering': ['store'], 'verbose_name': 'producto en venta', 'verbose_name_plural': 'productos en venta'},
        ),
    ]
