# Generated by Django 3.2 on 2024-09-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0015_alter_product_sales_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_sales',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Cantidad del producto en el almacén'),
        ),
    ]
