# Generated by Django 3.2 on 2024-09-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_product_sales_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='price',
        ),
        migrations.AddField(
            model_name='store',
            name='price_cup',
            field=models.FloatField(default=0, verbose_name='Precio de entrega en CUP'),
        ),
        migrations.AddField(
            model_name='store',
            name='price_mlc',
            field=models.FloatField(default=0, verbose_name='Precio de entrega en MLC'),
        ),
        migrations.AddField(
            model_name='store',
            name='price_usd',
            field=models.FloatField(default=0, verbose_name='Precio de entrega en USD'),
        ),
    ]
